apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: newsman
          artifact-id: 7f5d49e4-1ffd-4c46-a052-10e6cbcf15d7
          target-environment: QA
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: nodes
          artifact-id: f142ae34-1960-4604-ae84-59c0cc3f4fcd
          target-environment: qa2