apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: newsman
          artifact-id: 251ebfb2-c332-4bde-a424-a3bab02bcef7
          target-environment: QA
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: nodes
          artifact-id: 251ebfb2-c332-4bde-a424-a3bab02bcef7
          target-environment: qa2